### ISSUE TITLE
rename SDKs?

### ISSUE THREAD

**Issue by stevenou** [InvisibleCommerce/shipped-shield-ios-sdk#16]
what will it take to rename the SDKs?

i am thinking it should become `shipped-suite-ios-client-sdk` for these reasons:
1. adding `green` functionality means it's not just a `shipped-shield` sdk but a `shipped-suite` sdk
2. in anticipation of backend sdks (node js, ruby, python, php, etc) for server-to-server integration, i think it makes sense to specify that this is a `client` sdk

**Comment by stevenou** [comment]
@hoyelo can you assess what would be required to change these (without breaking existing integrations)?
e.g. changing repo name, changing the packages that are published, etc.

**Comment by hoyelo** [comment]
@stevenou If changes are made on an existing repo that would break the existing integration, it is possible to avoid these problems by creating a new repo that allows users to upgrade with the new package name and repo URL. 

<img width="860" alt="Screen Shot 2022-07-12 at 15 14 47" src="https://user-images.githubusercontent.com/3202811/178430985-bcff8a58-d665-4d32-857e-c265c1d41502.png">

We can do this entirely as a new SDK, so that the old headers and class names can be updated to `ShippedSuite` when the user reintegrates.

**Comment by stevenou** [comment]
ok. please coordinate with @catalin-invisible to make sure the new names and interfaces are consistent with JS.
